# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "staging"
    groups:
      web-framework:
        patterns:
          - "fastapi*"
          - "starlette*"
          - "uvicorn*"
      dev-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "fastapi*"
          - "starlette*"
          - "uvicorn*"
    ignore:
      - dependency-name: "pgvector"
        versions: [">=0.3.1"]
      # Ignore starlette versions that are incompatible with current fastapi
      - dependency-name: "starlette"
        versions: [">=0.47.0"]
      # Ignore fastapi versions that might introduce starlette compatibility issues
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]