[project]
name = "aibtcdev-backend"
version = "0.1.0"
description = "A sophisticated FastAPI-based backend service that powers AI-driven interactions with Bitcoin and Stacks blockchain technologies, providing real-time chat with AI agents, DAO management, social media integration, blockchain interaction capabilities, market data analysis, and document processing with vector search."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp==3.11.18",
    "apscheduler==3.11.0",
    "cachetools==5.5.2",
    "fastapi==0.115.12",
    "langchain==0.3.25",
    "langchain-community==0.3.23",
    "langchain-core>=0.3.56,<1.0.0",
    "langchain-openai==0.3.16",
    "langchain-text-splitters==0.3.8",
    "langgraph==0.4.1",
    "openai==1.77.0",
    "pgvector==0.3.6",
    "psycopg2==2.9.10",
    "pydantic==2.11.4",
    "python-dotenv==1.1.0",
    "python-telegram-bot==22.0",
    "python-twitter-v2==0.9.2",
    "requests==2.32.3",
    "sqlalchemy==2.0.40",
    "starlette==0.46.2",
    "supabase==2.15.1",
    "tiktoken==0.9.0",
    "uvicorn==0.34.2",
    "vecs==0.4.5",
]
[project.optional-dependencies]
testing = [
    "pytest==8.3.5",
    "pytest-asyncio==0.26.0",
    "pytest-mock==3.14.0",
    "responses==0.25.7",
]