name: Build Docker Image

on:
  pull_request:
    branches: ["main"]

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix={{branch}}-

